<?php

namespace MayMeow\Tests\Features;

use MayMeow\Loaders\FileLoader;
use MayMeow\Tests\TestCase;
use MayMeow\Factory\CertificateFactory;
use MayMeow\Model\EncryptConfiguration;
use MayMeow\Writers\FileWriter;

class SigningCertificatesTest extends TestCase
{
    protected $certificateFactory;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->certificateFactory = new CertificateFactory(new EncryptConfiguration());
    }

    /** @test */
    function user_can_create_CA_certificate()
    {
        $this->certificateFactory->domainName()
            ->setOrganizationName('Test CA')
            ->setCountryName('SK')
            ->setCommonName('Test Root CA');

        $this->certificateFactory->setType(CertificateFactory::TYPE_CERTIFICATION_AUTHORITY)
            ->setName('test-ca')
            ->sign()->using(FileWriter::class)->write();

        $this->assertTrue(file_exists(WWW_ROOT . 'test-ca' . DS . 'cert.crt'));
    }

    /** @test */
    function user_can_sign_intermediate_CA_certificate()
    {
        $this->certificateFactory->domainName()
            ->setOrganizationName('Test CA')
            ->setCountryName('SK')
            ->setOrganizationalUnitName('Intermediate Certificate authority')
            ->setCommonName('Test Intermediate CA');

        $this->certificateFactory->setType(CertificateFactory::TYPE_INTERMEDIATE)
            ->setName('test-intermediate-ca')
            ->setCaFrom(new FileLoader('test-ca'))
            ->sign()->using(FileWriter::class)->write();

        $this->assertTrue(file_exists(WWW_ROOT . 'test-intermediate-ca' . DS . 'cert.crt'));
    }

    /** @test */
    function user_can_create_user_certificate()
    {
        $this->certificateFactory->domainName()
            ->setOrganizationName('Test Organization')
            ->setCountryName('SK')
            ->setOrganizationalUnitName('Test Organization Unit')
            ->setCommonName('Jane Doe');

        $this->certificateFactory->setType(CertificateFactory::TYPE_USER)
            ->setName('test-user_certificate')
            #->setCa('test-intermediate-ca', file_get_contents(WWW_ROOT . 'test-intermediate-ca' . DS . 'code.txt'))
            ->setCaFrom(new FileLoader('test-intermediate-ca'))
            ->sign()->using(FileWriter::class)->write();

        $this->assertTrue(file_exists(WWW_ROOT . 'test-user_certificate' . DS . 'cert.crt'));
    }

    /** @test */
    function user_can_create_server_certificate()
    {
        $this->certificateFactory->domainName()
            ->setOrganizationName('Test Organization')
            ->setCountryName('SK')
            ->setOrganizationalUnitName('Test Organization Unit')
            ->setCommonName('webserver.dev');

        $this->certificateFactory->getAltNames()
            ->setDns("webserver.dev")
            ->setDns("*.webserver.dev")
            ->setIp("10.0.0.1");

        $this->certificateFactory->setType(CertificateFactory::TYPE_SERVER)
            ->setName('test-server-certificate')
            #->setCa('test-intermediate-ca', file_get_contents(WWW_ROOT . 'test-intermediate-ca' . DS . 'code.txt'))
            ->setCaFrom(new FileLoader('test-intermediate-ca'))
            ->sign()
            ->using(FileWriter::class)->write();

        $this->assertTrue(file_exists(WWW_ROOT . 'test-user_certificate' . DS . 'cert.crt'));
    }

    /** @test */
    function user_can_sign_intermediate_code_sign_certificate()
    {
        $this->certificateFactory->domainName()
            ->setOrganizationName('Test Organization')
            ->setCountryName('SK')
            ->setOrganizationalUnitName('Test Organization Unit')
            ->setCommonName('Jane Doe');

        $this->certificateFactory->setType(CertificateFactory::TYPE_CODE_SIGN)
            ->setName('test-user_certificate')
            ->setCaFrom(new FileLoader('test-intermediate-ca'))
            ->sign()->using(FileWriter::class)->write();

        $this->assertTrue(file_exists(WWW_ROOT . 'test-user_certificate' . DS . 'cert.crt'));
    }
}