language: php
php:
    - '7.1'
    - '7.2'
    - hhvm
    - nightly

matrix:
    allow_failures:
    - php: hhvm
    - php: nightly

before_script:
    - composer self-update
    - composer install

script:
    - phpunit --coverage-text