name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: PHPUnit Test by MayMeow
      uses: MayMeowHQ/PHPUnit-Test-Action@v5
